Lab1. MovieWebApplication/MoviesWebApplication/Models/Production.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MoviesWebApplication
{
    public partial class Production
    {
        public Production()
        {
            Movies = new HashSet<Movie>();
        }

        public int Id { get; set; }

        [Display(Name = "Назва")]
        public string Name { get; set; } = null!;

        [Display(Name = "Країна")]
        public string Country { get; set; } = null!;

        [Display(Name = "Фільми")]
        public virtual ICollection<Movie> Movies { get; set; }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/ProductionsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class ProductionsController : Controller
    {
        private readonly MovieDBContext _context;

        public ProductionsController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Productions
        public async Task<IActionResult> ProductionList()
        {
            return View(await _context.Productions.ToListAsync());
        }

        // GET: Productions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var production = await _context.Productions
                .Include(p => p.Movies)
                .FirstOrDefaultAsync(m => m.Id == id);

            var currentProduction = _context.Productions.FirstOrDefault(p => p.Id == id);

            ViewBag.CurrentProductionName = currentProduction.Name;
            ViewBag.Sum = from movie in _context.Movies group movie by movie.Production into prodByMovie select new { Production = prodByMovie.Key, TotalDuration = prodByMovie.Sum(movie => movie.Duration) };

            if (production == null)
            {
                return NotFound();
            }

            return View(production);
        }

        // GET: Productions/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Productions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Country")] Production production)
        {
            if (ModelState.IsValid)
            {
                _context.Add(production);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ProductionList));
            }
            return View(production);
        }

        // GET: Productions/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var production = await _context.Productions.FindAsync(id);
            if (production == null)
            {
                return NotFound();
            }
            return View(production);
        }

        // POST: Productions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Country")] Production production)
        {
            if (id != production.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(production);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductionExists(production.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ProductionList));
            }
            return View(production);
        }

        // GET: Productions/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var production = await _context.Productions
    .Include(p => p.Movies)
    .FirstOrDefaultAsync(m => m.Id == id);
            if (production == null)
            {
                return NotFound();
            }

            return View(production);
        }

        // POST: Productions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var production = await _context.Productions.FindAsync(id);
            _context.Productions.Remove(production);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ProductionList));
        }

        private bool ProductionExists(int id)
        {
            return _context.Productions.Any(e => e.Id == id);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
                        {
                            RemoveUnmentionedProductions(workBook.Worksheets.Select(w => w.Name.ToLower()).ToList());
                            foreach (IXLWorksheet worksheet in workBook.Worksheets)
                            {
                                ProcessImportedProduction(worksheet);
                            }
                        }
                    }
                }

                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(ProductionList));
        }

        public ActionResult Export()
        {
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var productions = _context.Productions.Include("Movies").ToList();

                foreach (var p in productions)
                {
                    var worksheet = workbook.Worksheets.Add(p.Name);

                    worksheet.Cell("A1").Value = "Назва";
                    worksheet.Cell("B1").Value = "Тривалість фільму";
                    worksheet.Cell("C1").Value = "Чи є оскар";
                    worksheet.Cell("D1").Value = "Жанри";
                    worksheet.Row(1).Style.Font.Bold = true;
                    var movies = p.Movies.ToList();

                    //нумерація рядків/стовпчиків починається з індекса 1 (не 0)
                    for (int i = 0; i < movies.Count; i++)
                    {
                        worksheet.Cell(i + 2, 1).Value = movies[i].Name;
                        worksheet.Cell(i + 2, 2).Value = movies[i].Duration;
                        worksheet.Cell(i + 2, 3).Value = movies[i].HasOscar;

                        var mgg = _context.MoviesGenres.Where(mg => mg.MovieId == movies[i].Id).Include("Genre").ToList();

                        int j = 0;
                        foreach (var g in mgg)
                        {
                            worksheet.Cell(i + 2, 4 + j).Value = g.Genre.Name;
                            j++;
                        }
                    }
                }
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    stream.Flush();

                    return new FileContentResult(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        //змініть назву файла відповідно до тематики Вашого проєкту

                        FileDownloadName = $"MovieBase_{DateTime.UtcNow.ToShortDateString()}.xlsx"
                    };
                }
            }
        }

        private void RemoveUnmentionedProductions(List<string> productionNamesInLowerCase)
        {
            var productions = _context.Productions.Where(p =>
                !productionNamesInLowerCase.Contains(p.Name.ToLower())).ToList();

            foreach(var production in productions)
            {
                _context.Productions.Remove(production);
            }
        }

        private void ProcessImportedProduction(IXLWorksheet worksheet)
        {
            //worksheet.Name - назва категорії. Пробуємо знайти в БД, якщо відсутня, то створюємо нову
            Production production = _context.Productions
                .FirstOrDefault(p => p.Name.ToLower() == worksheet.Name.ToLower());

            if (production == null)
            {
                production = new Production();
                production.Name = worksheet.Name;
                production.Country = "from Excel";

                //додати в контекст
                _context.Productions.Add(production);
            }

            RemoveUnmentionedMovies(
                worksheet.RowsUsed().Skip(1).Select(r => r.Cell(1).GetString().ToLower()).ToList(),
                production.Id);

            //перегляд усіх рядків                    
            foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
            {
                ProcessImportedMovie(row, production);
            }
        }

        private void RemoveUnmentionedMovies(List<string> movieNamesInLowerCase, int productionId)
        {
            var movies = _context.Movies.Where(m =>
                !movieNamesInLowerCase.Contains(m.Name.ToLower()) && m.ProductionId == productionId).ToList();

Lab1. MovieWebApplication/MoviesWebApplication/Views/Productions/Create.cshtml
@model MoviesWebApplication.Production

@{
    ViewData["Title"] = "Create";
}

<h1>Додати кіностудію</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Додати" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ProductionList">Повернутися назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab1. MovieWebApplication/MoviesWebApplication/Views/Productions/Delete.cshtml
@model MoviesWebApplication.Production

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалення</h1>

<h3>Ви впевнені, що хочете видалити цю кінокомпанію та всі її фільми?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Movies)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Movies)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "Details", "Movies", routeValues: new {id = item.Id})
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="ProductionList">Повернутися назад</a>
    </form>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/Productions/Details.cshtml
@model MoviesWebApplication.Production

<h1>Кінокомпанія @ViewBag.CurrentProductionName</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Movies)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model.Movies) {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Details", "Movies", routeValues: new {id = item.Id})
            </td>
        </tr>
}
    </tbody>
</table>

</div>
<div>
@*    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |*@
    <a asp-action="ProductionList">Повернутися назад</a>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/Productions/Edit.cshtml
@model MoviesWebApplication.Production

@{
    ViewData["Title"] = "Edit";
}

<h1>Внести зміни</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти зміни" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ProductionList">Повернутися назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab1. MovieWebApplication/MoviesWebApplication/Views/Productions/ProductionList.cshtml
@model IEnumerable<MoviesWebApplication.Production>

@{
    ViewData["Title"] = "Index";
}

<h1>Провідні кінокомпанії світу</h1>


<h5>Завантаження інформації з файлу</h5>
@using (Html.BeginForm("Import", "Productions", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
{
    <div>
        <input type="file" name="fileExcel" id="fileExcel" /> <input type="submit" value="Завантажити" />
    </div>
}

    <h5>Вивантаження інформації у файл</h5>
    <form method="post" asp-controller="Productions" asp-action="Export"> <input type="submit" value="Вивантажити" /> 
    </form>

<p>
    @{
    if (User.IsInRole("admin"))
    {
        <form method="post" asp-controller="Productions" asp-action="Create">
            <input type="submit" value="Додати кіностудію" />
        </form>
    }
}
</p>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Роботи кінокомпанії</a>
                    @{
                        if (User.IsInRole("admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.Id">| Видалити |</a>
                            <a asp-action="Edit" asp-route-id="@item.Id">Змінити</a>
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="container">
    <div id="chart1"></div>
</div>
@section scripts{
<script type "text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    google.charts.load('current', { 'packages': ['corechart'] });
    google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

            $.get('/api/Charts/JsonData1', function(JsonData1) {
                data = google.visualization.arrayToDataTable(JsonData1, false);
                var option = {
                    title: "Співвідношення кількості фільмів та кінокомпаній",
                    width: 500,
                    height: 400
                };
                chart = new google.visualization.PieChart(document.getElementById('chart1'));
                chart.draw(data, option);
            })
        }
</script>
}