Lab1. MovieWebApplication/MoviesWebApplication/Models/MoviesGenre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MoviesWebApplication
{
    public partial class MoviesGenre
    {
        public int Id { get; set; }

        [Display(Name = "Фільм")]
        public int MovieId { get; set; }

        [Display(Name = "Жанр")]
        public int GenreId { get; set; }

        public virtual Genre? Genre { get; set; }

        [Display(Name = "Фільми")]
        public virtual Movie? Movie { get; set; }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/GenresController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class GenresController : Controller
    {
        private readonly MovieDBContext _context;

        public GenresController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> GenresList()
        {
            return View(await _context.Genres.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(GenresList));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = await _context.Genres.FindAsync(id);
            _context.Genres.Remove(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(GenresList));
        }

        private bool GenreExists(int id)
        {
            return _context.Genres.Any(e => e.Id == id);
        }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/MoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieDBContext _context;

        public MoviesController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> List()
        {
            var movieDBContext = _context.Movies.Include(m => m.Production);
            return View(await movieDBContext.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Production)
                .Include(m => m.ArtistsJobsInMovies)
                .ThenInclude(am => am.Artist)
                .Include(m => m.MoviesGenres)
                .ThenInclude(mg => mg.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Duration,HasOscar,ProductionId")] Movie movie)
        {
            Production pr = _context.Productions.FirstOrDefault(p => p.Id == movie.ProductionId);
            movie.Production = pr;

            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }

            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name", movie.ProductionId);
            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name", movie.ProductionId);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Duration,HasOscar,ProductionId")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(List));
            }
            ViewData["ProductionId"] = new SelectList(_context.Productions, "Id", "Id", movie.ProductionId);
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Production)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }


    }


}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/MoviesGenresController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class MoviesGenresController : Controller 
    {
        private readonly MovieDBContext _context;

        public MoviesGenresController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: MoviesGenres
        public async Task<IActionResult> GenreMoviesList(int genreId) 
        {
            var currentGenre = _context.Genres.FirstOrDefault(g => g.Id == genreId);

            if(currentGenre == null)
            {
                return NotFound();
            }

            ViewBag.CurrentGenre = currentGenre;

            var movieDBContext = await _context.MoviesGenres
                .Where(mg => mg.GenreId == genreId)
                .Include(mg => mg.Movie).ToListAsync();

            return View(movieDBContext);
        } 

        // GET: MoviesGenres/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create(int currentGenreId)
        {
            var currentGenre = _context.Genres.FirstOrDefault(g => g.Id == currentGenreId);
            var currentGenreMovieIds = _context.MoviesGenres.Where(mg => mg.GenreId == currentGenreId).Select(mg => mg.MovieId);
            ViewBag.CurrentGenre = currentGenre;
            ViewBag.MoviesList = new SelectList(_context.Movies.Where(m => !currentGenreMovieIds.Contains(m.Id)), "Id", "Name");
            return View(); 
        }

        // POST: MoviesGenres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRes([Bind("Id,MovieId,GenreId")] MoviesGenre moviesGenre)
        {
            Genre genre = _context.Genres.FirstOrDefault(x => x.Id == moviesGenre.GenreId);
            if (ModelState.IsValid)
            {
                Movie movie = _context.Movies.FirstOrDefault(x => x.Id == moviesGenre.MovieId);
                moviesGenre.Movie = movie;
                moviesGenre.Genre = genre;
                _context.Add(moviesGenre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(GenreMoviesList), new { genreId = genre.Id });
            }
            var currentGenreMovieIds = _context.MoviesGenres.Where(mg => mg.GenreId == genre.Id).Select(mg => mg.MovieId);
            ViewBag.GenreId = genre.Id;
            ViewBag.GenreName = genre.Name;
            ViewBag.MoviesList = new SelectList(_context.Movies.Where(m => !currentGenreMovieIds.Contains(m.Id)), "Id", "Name", moviesGenre.MovieId);
            return View(moviesGenre);
        }

        // GET: MoviesGenres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var moviesGenre = await _context.MoviesGenres
                .Include(mg => mg.Genre)
                .Include(mg => mg.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (moviesGenre == null)
            {
                return NotFound();
            }

            ViewBag.CurrentGenre = moviesGenre.Genre;

            return View(moviesGenre);
        }

        // POST: MoviesGenres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moviesGenre = await _context.MoviesGenres
                .FindAsync(id);
            _context.MoviesGenres.Remove(moviesGenre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(GenreMoviesList), new { genreId = moviesGenre.GenreId });
        }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesGenres/Create.cshtml
@model MoviesWebApplication.MoviesGenre

<h1>Додавання фільму</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <label>@ViewBag.CurrentGenre.Name</label>
                <input type="hidden" asp-for="GenreId" value="@ViewBag.CurrentGenre.Id" />
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="@ViewBag.MoviesList as SelectList"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div> 
</div>

<div>
    <a asp-action="GenreMoviesList" asp-route-genreId="@ViewBag.CurrentGenre.Id">Повернутися назад</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesGenres/Delete.cshtml
@model MoviesWebApplication.MoviesGenre

<h1>Видалення</h1>

<h3>Ви впевнені, що хочете видалити жанр "@Model.Genre?.Name" для фільму "@Model.Movie?.Name"?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10"> 
            @Html.DisplayFor(model => model.Movie.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="GenreMoviesList" asp-route-genreId="@ViewBag.CurrentGenre.Id">Повернутися назад</a>
    </form>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesGenres/Details.cshtml
@model MoviesWebApplication.MoviesGenre

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MoviesGenre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesGenres/Edit.cshtml
@model MoviesWebApplication.MoviesGenre

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MoviesGenre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesGenres/GenreMoviesList.cshtml
@model IEnumerable<MoviesWebApplication.MoviesGenre>

<h1>Фільми жанру: </h1>
<h1>@ViewBag.CurrentGenre.Name</h1>

@{
    if (User.IsInRole("admin"))
    {
        <form method="post" asp-controller="MoviesGenres" asp-action="Create" asp-route-currentGenreId="@ViewBag.CurrentGenre.Id">
            <input type="submit" value="Додати фільм" />
        </form>
    }
}

<table class="table">
    <thead>
        <tr> 
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Movie.Name, "Details", "Movies", routeValues: new {id = @item.Movie.Id})
                </td>

                <td>
                    @{
                        if (User.IsInRole("admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    @Html.ActionLink("Повернутися назад", "GenresList" ,"Genres" )
</div>