Lab1. MovieWebApplication/MoviesWebApplication/Models/MoviesInPlaylist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MoviesWebApplication
{
    public partial class MoviesInPlaylist
    {
        public int Id { get; set; }

        [Display(Name = "Назва фільму")]
        public int MovieId { get; set; }

        [Display(Name = "Назва підбірки")]
        public int PlaylistId { get; set; }


        [Display(Name = "Фільм")]
        public virtual Movie? Movie { get; set; }

        [Display(Name = "Підбірка")]
        public virtual Playlist? Playlist { get; set; }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/MoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieDBContext _context;

        public MoviesController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> List()
        {
            var movieDBContext = _context.Movies.Include(m => m.Production);
            return View(await movieDBContext.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Production)
                .Include(m => m.ArtistsJobsInMovies)
                .ThenInclude(am => am.Artist)
                .Include(m => m.MoviesGenres)
                .ThenInclude(mg => mg.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Duration,HasOscar,ProductionId")] Movie movie)
        {
            Production pr = _context.Productions.FirstOrDefault(p => p.Id == movie.ProductionId);
            movie.Production = pr;

            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }

            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name", movie.ProductionId);
            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name", movie.ProductionId);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Duration,HasOscar,ProductionId")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(List));
            }
            ViewData["ProductionId"] = new SelectList(_context.Productions, "Id", "Id", movie.ProductionId);
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Production)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }


    }


}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/MoviesInPlaylistsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class MoviesInPlaylistsController : Controller
    {
        private readonly MovieDBContext _context;

        public MoviesInPlaylistsController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: MoviesInPlaylists
        public async Task<IActionResult> PlaylistMovies(int playlistId)
        {
            var currentPlaylist = _context.Playlists.FirstOrDefault(p=>p.Id==playlistId);
            if (currentPlaylist == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPlaylist = currentPlaylist;
            ViewBag.PlaylistUserName = _context.Playlists.Where(p => p.Id == playlistId).Select(p => p.UserName).Single();

            var movieDBContext = await _context.MoviesInPlaylists.Where(mp=>mp.PlaylistId==playlistId)
                .Include(m => m.Movie).ToListAsync();

            return View(movieDBContext);
        }

        // GET: MoviesInPlaylists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moviesInPlaylist = await _context.MoviesInPlaylists
                .Include(m => m.Movie)
                .Include(m => m.Playlist)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (moviesInPlaylist == null)
            {
                return NotFound();
            }

            return View(moviesInPlaylist);
        }

        // GET: MoviesInPlaylists/Create
        public IActionResult Create(int currentPlaylistId)
        {
            var currentPlaylist = _context.Playlists.FirstOrDefault(p => p.Id == currentPlaylistId);
            var currentPlaylistMovieIds = _context.MoviesInPlaylists.Where(mp => mp.PlaylistId == currentPlaylistId).Select(mp => mp.MovieId);
            ViewBag.CurrentPlaylist = currentPlaylist;
            ViewBag.MoviesList = new SelectList(_context.Movies.Where(m => !currentPlaylistMovieIds.Contains(m.Id)), "Id", "Name");
            return View();
        }

        // POST: MoviesInPlaylists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRes([Bind("Id,MovieId,PlaylistId")] MoviesInPlaylist moviesInPlaylist)
        {
            Playlist playlist = _context.Playlists.FirstOrDefault(x => x.Id == moviesInPlaylist.PlaylistId);
            if (ModelState.IsValid)
            {
                Movie movie = _context.Movies.FirstOrDefault(x => x.Id == moviesInPlaylist.MovieId);
                moviesInPlaylist.Movie = movie;
                moviesInPlaylist.Playlist = playlist;
                _context.Add(moviesInPlaylist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(PlaylistMovies), new { playlistId = playlist.Id });
            }
            var currentPlaylistMovieIds = _context.MoviesInPlaylists.Where(mp => mp.PlaylistId == playlist.Id).Select(mp => mp.MovieId);
            ViewBag.CurrentPlaylist = playlist;
            ViewBag.MoviesList = new SelectList(_context.Movies.Where(m => !currentPlaylistMovieIds.Contains(m.Id)), "Id", "Name", moviesInPlaylist.MovieId);
            return View(moviesInPlaylist);
        }

        // GET: MoviesInPlaylists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moviesInPlaylist = await _context.MoviesInPlaylists
                .Include(m => m.Movie)
                .Include(m => m.Playlist)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (moviesInPlaylist == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPlaylist = _context.MoviesInPlaylists.Where(mp => mp.Id == id).Select(mp => mp.Playlist).Single();
            ViewBag.CurrentMovie = _context.MoviesInPlaylists.Where(mp => mp.Id == id).Select(mp => mp.Movie).Single();

            return View(moviesInPlaylist);
        }

        // POST: MoviesInPlaylists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moviesInPlaylist = await _context.MoviesInPlaylists.FindAsync(id);
            _context.MoviesInPlaylists.Remove(moviesInPlaylist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(PlaylistMovies), new { playlistId = moviesInPlaylist.PlaylistId });
        }

        private bool MoviesInPlaylistExists(int id)
        {
            return _context.MoviesInPlaylists.Any(e => e.Id == id);
        }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Controllers/PlaylistsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;
using MoviesWebApplication.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace MoviesWebApplication.Controllers
{
    public class PlaylistsController : Controller
    {
        private readonly MovieDBContext _context;

        public PlaylistsController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Playlists
        //[Authorize(Roles = "admin, user")]
        public async Task<IActionResult> PlayList()
        {
            return View(await _context.Playlists.ToListAsync());
        }

        // GET: Playlists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // GET: Playlists/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Playlists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRes([Bind("Id,Name,UserName")] Playlist playlist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(playlist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(PlayList));
            }
            return View(playlist);
        }

        // GET: Playlists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlists.FindAsync(id);
            if (playlist == null)
            {
                return NotFound();
            }
            return View(playlist);
        }

        // POST: Playlists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UserName")] Playlist playlist)
        {
            if (id != playlist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(playlist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaylistExists(playlist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(PlayList));
            }
            return View(playlist);
        }

        // GET: Playlists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.CurrentPlaylist = _context.Playlists.Single(p => p.Id == id);
            if (id == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // POST: Playlists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var playlist = await _context.Playlists.FindAsync(id);
            _context.Playlists.Remove(playlist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(PlayList));
        }

        private bool PlaylistExists(int id)
        {
            return _context.Playlists.Any(e => e.Id == id);
        }
    }
}

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesInPlaylists/Create.cshtml
@model MoviesWebApplication.MoviesInPlaylist

<h4>Виберіть фільм, який ви хочете додати до збірки "@ViewBag.CurrentPlaylist.Name"</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlaylistId" class="control-label"></label>
                <label>"@ViewBag.CurrentPlaylist.Name"</label>
                <input type="hidden" asp-for="PlaylistId" value="@ViewBag.CurrentPlaylist.Id" />
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="@ViewBag.MoviesList as SelectList"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Додати" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PlaylistMovies">Повернутися назад</a>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesInPlaylists/Delete.cshtml
@model MoviesWebApplication.MoviesInPlaylist


<h3>Ви впевнені, що хочете видалити фільм "@ViewBag.CurrentMovie.Name" з підбірки "@ViewBag.CurrentPlaylist.Name"?</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="PlaylistMovies" asp-route-playlistId="@ViewBag.CurrentPlaylist.Id">Повернутися назад</a>
    </form>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesInPlaylists/Details.cshtml
@model MoviesWebApplication.MoviesInPlaylist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MoviesInPlaylist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Playlist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Playlist.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesInPlaylists/Edit.cshtml
@model MoviesWebApplication.MoviesInPlaylist

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MoviesInPlaylist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaylistId" class="control-label"></label>
                <select asp-for="PlaylistId" class="form-control" asp-items="ViewBag.PlaylistId"></select>
                <span asp-validation-for="PlaylistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Lab1. MovieWebApplication/MoviesWebApplication/Views/MoviesInPlaylists/PlaylistMovies.cshtml
@model IEnumerable<MoviesWebApplication.MoviesInPlaylist>


<h2>Фільми, що входять до підбірки "@ViewBag.CurrentPlaylist.Name"</h2>

@{
    if (@User.Identity.Name == @ViewBag.PlaylistUserName || User.IsInRole("admin"))
    {
        <form method="post" asp-controller="MoviesInPlaylists" asp-action="Create" asp-route-currentPlaylistId="@ViewBag.CurrentPlaylist.Id">
            <input type="submit" value="Додати фільм до підбірки" />
        </form>

    }
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Movie.Name, "Details", "Movies", routeValues: new {id = @item.Movie.Id})
                </td>

                @{
                    if (@User.Identity.Name == @ViewBag.PlaylistUserName || User.IsInRole("admin"))
                    {
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

<div>
    @Html.ActionLink("Повернутися назад", "PlayList" ,"Playlists" )
</div>